version: '3'

name: sponge

services:
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_vol:/data
      - zookeeper_vol:/datalog
      - zookeeper_vol:/logs
    container_name: zookeeper

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "localhost"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LOG_DIRS: "/kafka/logs"
    volumes:
      - kafka_vol:/kafka
    depends_on:
      - zookeeper
    container_name: kafka
  
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - mysql_vol:/var/lib/mysql
    ports:
      - 3306:3306

  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - redis_vol:/data
    ports:
      - 6379:6379


volumes:
  zookeeper_vol: {}
  kafka_vol: {}
  mysql_vol: {}
  redis_vol: {}