version: '3'
name: sponge
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - mysql_vol:/var/lib/mysql
    ports:
      - 3306:3306

  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - redis_vol:/data
    ports:
      - 6379:6379
  
  server-1:
    container_name: server-1
    environment:
      - TARGET_APP=server
    build:
      context: .
      dockerfile: dockerfile
    command: ["0.0.0.0", "8000"]
    volumes:
      - server1_vol:/sponge/logs
    ports:
      - 8000:8000
    depends_on:
      - mysql
      - redis

volumes:
  mysql_vol: {}
  redis_vol: {}
  server1_vol: {}