version: '3'
name: sponge
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - mysql_vol:/var/lib/mysql
    ports:
      - 3306:3306

  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - redis_vol:/data
    ports:
      - 6379:6379


volumes:
  mysql_vol: {}
  redis_vol: {}